# Generated by Django 4.2.3 on 2023-07-27 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='Начало встречи')),
                ('end', models.DateTimeField(verbose_name='Конец встречи')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Отказано'), (2, 'В ожидании'), (3, 'Ждут ответа'), (4, 'Активно')], default=2, verbose_name='Статус')),
                ('answer', models.BooleanField(default=False, verbose_name='Ответ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('invited', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited', to=settings.AUTH_USER_MODEL, verbose_name='Приглашённый')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inviter', to=settings.AUTH_USER_MODEL, verbose_name='Пригласитель')),
            ],
            options={
                'verbose_name': 'B2B Встреча',
                'verbose_name_plural': 'B2B Встречи',
            },
        ),
    ]
