# Generated by Django 3.2.9 on 2023-07-31 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b_meeting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='answer_en',
            field=models.BooleanField(default=False, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='answer_ru',
            field=models.BooleanField(default=False, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
