# Generated by Django 3.2.9 on 2023-07-31 08:10

import apps.main_page.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание форма'),
        ),
        migrations.AddField(
            model_name='forum',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание форма'),
        ),
        migrations.AddField(
            model_name='forum',
            name='title_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Заголовок форма'),
        ),
        migrations.AddField(
            model_name='forum',
            name='title_ru',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Заголовок форма'),
        ),
        migrations.AddField(
            model_name='pageone',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание Экспо'),
        ),
        migrations.AddField(
            model_name='pageone',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание Экспо'),
        ),
        migrations.AddField(
            model_name='pageone',
            name='title_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Заголовок Экспо'),
        ),
        migrations.AddField(
            model_name='pageone',
            name='title_ru',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Заголовок Экспо'),
        ),
        migrations.AddField(
            model_name='sectors',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание сектора'),
        ),
        migrations.AddField(
            model_name='sectors',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание сектора'),
        ),
        migrations.AddField(
            model_name='sectors',
            name='image_en',
            field=models.ImageField(blank=True, null=True, upload_to=apps.main_page.services.get_upload_path, verbose_name='Фотография'),
        ),
        migrations.AddField(
            model_name='sectors',
            name='image_ru',
            field=models.ImageField(blank=True, null=True, upload_to=apps.main_page.services.get_upload_path, verbose_name='Фотография'),
        ),
        migrations.AddField(
            model_name='sectors',
            name='title_en',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Заголовок сектора'),
        ),
        migrations.AddField(
            model_name='sectors',
            name='title_ru',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Заголовок сектора'),
        ),
        migrations.AddField(
            model_name='target',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание цели'),
        ),
        migrations.AddField(
            model_name='target',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание цели'),
        ),
        migrations.AddField(
            model_name='target',
            name='title_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Заголовок цели'),
        ),
        migrations.AddField(
            model_name='target',
            name='title_ru',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Заголовок цели'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание задач'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание задач'),
        ),
        migrations.AddField(
            model_name='video',
            name='title_en',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='video',
            name='title_ru',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Заголовок'),
        ),
    ]
