version: "3.8"

services:
  web:
    build: .
    restart: always
    command: sh -c "python manage.py collectstatic --no-input && python manage.py migrate && gunicorn -w 7 -b 0.0.0.0:8000 main.wsgi --reload && daphne main.asgi:application"
    volumes:
      - .:/app
      - ./media:/app/media/
      - ./static:/app/static/
    ports:
      - "8000:8000"
    depends_on:
      - pgdb

  pgdb:
    image: postgres:latest
    container_name: pgdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=expo_db
      - POSTGRES_USER=hit_expo
      - POSTGRES_PASSWORD=expo_123
      - PORT=5432

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./lets:/etc/letsencrypt
      - ./media:/usr/share/nginx/html/media
      - ./static:/usr/share/nginx/html/static

volumes:
  postgres_data:
  lets: