version: "3.8"

services:
  web:
    build: .
    restart: always
    command: sh -c "python manage.py collectstatic --no-input && python manage.py migrate && gunicorn -w 7 -b 0.0.0.0:8000 main.wsgi --reload && daphne main.asgi:application"
    volumes:
      - .:/app
      - ./media:/app/media/
      - ./static:/app/static/
    expose:
      - "8000"

  pgdb:
    image: postgres:latest
    container_name: pgdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=expo_db
      - POSTGRES_USER=hit_expo
      - POSTGRES_PASSWORD=expo_123
      - PORT=5432

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  # Путь к конфигурационному файлу Nginx
    depends_on:
      - web

volumes:
  postgres_data:
