# Generated by Django 3.2.9 on 2023-07-31 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion_zone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalinformation',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='additionalinformation',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='additionalinformation',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='additionalinformation',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='advantages',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='advantages',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='advantages',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='advantages',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='advantageszone',
            name='block_title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='advantageszone',
            name='block_title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='brackets',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='brackets',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='brackets',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='brackets',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='bracketszone',
            name='subtext_en',
            field=models.TextField(null=True, verbose_name='Подописание'),
        ),
        migrations.AddField(
            model_name='bracketszone',
            name='subtext_ru',
            field=models.TextField(null=True, verbose_name='Подописание'),
        ),
        migrations.AddField(
            model_name='bracketszone',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='bracketszone',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='fashionzone',
            name='block_title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Заглавный текст'),
        ),
        migrations.AddField(
            model_name='fashionzone',
            name='block_title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Заглавный текст'),
        ),
        migrations.AddField(
            model_name='fashionzone',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='fashionzone',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='fashionzone',
            name='header_photo_en',
            field=models.ImageField(null=True, upload_to='media/invest_zone', verbose_name='Заглавное фото'),
        ),
        migrations.AddField(
            model_name='fashionzone',
            name='header_photo_ru',
            field=models.ImageField(null=True, upload_to='media/invest_zone', verbose_name='Заглавное фото'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='possibility',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='possibility',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='stage',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='stage',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='stage',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='stage',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Заголовок'),
        ),
    ]
