# Generated by Django 3.2.9 on 2023-07-25 10:07

import apps.ticket.services
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('payment_rekvizit', models.CharField(max_length=300, verbose_name='Реквизиты')),
                ('icon', models.ImageField(upload_to=apps.ticket.services.get_upload_path, verbose_name='Иконка')),
                ('chek_photo', models.ImageField(upload_to=apps.ticket.services.get_upload_path, validators=[apps.ticket.services.validate_file_extension], verbose_name='Фото чека')),
            ],
        ),
    ]
