# Generated by Django 3.2.9 on 2023-07-29 09:32

import apps.ticket.services
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chek_photo', models.ImageField(blank=True, null=True, upload_to=apps.ticket.services.get_upload_path, validators=[apps.ticket.services.validate_file_extension], verbose_name='Фото чека')),
            ],
            options={
                'verbose_name': 'Чек',
                'verbose_name_plural': 'Чеки',
                'db_table': 'ticket.check',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('payment_rekvizit', models.CharField(max_length=300, verbose_name='Реквизиты')),
                ('icon', models.ImageField(upload_to=apps.ticket.services.get_upload_path, verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
                'db_table': 'ticket',
            },
        ),
    ]
