# Generated by Django 3.2.9 on 2023-08-29 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trade_zone', '0002_auto_20230731_1410'),
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Отрасль',
                'verbose_name_plural': 'Отрасли',
            },
        ),
        migrations.CreateModel(
            name='Stand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('number_of_places', models.PositiveIntegerField(verbose_name='Кол-во мест')),
                ('size', models.CharField(max_length=300, verbose_name='Размер')),
                ('image', models.ImageField(upload_to='media/stands', verbose_name='Фото')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Цена')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('additionally', models.ManyToManyField(related_name='additionallys', to='trade_zone.Additionally', verbose_name='Дополнительно')),
                ('decor', models.ManyToManyField(related_name='decors', to='trade_zone.Decor', verbose_name='Оформление')),
            ],
            options={
                'verbose_name': 'Стенд',
                'verbose_name_plural': 'Стенды',
            },
        ),
        migrations.DeleteModel(
            name='Check',
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Билет', 'verbose_name_plural': 'Билеты на покупку стендов'},
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='payment_rekvizit',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='title',
        ),
        migrations.AddField(
            model_name='ticket',
            name='activities',
            field=models.CharField(default=1, max_length=500, verbose_name='Деятельность'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='line',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Линия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/ticket/check', verbose_name='Чек'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='place_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Gold'), (2, 'Silver'), (3, 'Standart'), (4, 'Шатер Invest zone'), (5, 'Шатер Trade zone')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='row',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Ряд'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Не оплачено'), (2, 'В обработке'), (3, 'Успешно')], default=1, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='zone',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Trade'), (2, 'Invest'), (3, 'Fashion'), (4, 'Food'), (5, 'National')], default=1, verbose_name='Зона'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='zone_numbering',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Номер зоны'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='ticket',
            table=None,
        ),
        migrations.AddField(
            model_name='ticket',
            name='industry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ticket.industry', verbose_name='Отрасль'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='stand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ticket.stand', verbose_name='Стенд'),
            preserve_default=False,
        ),
    ]
