# Generated by Django 3.2.9 on 2023-07-25 10:09

import apps.ticket.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='chek_photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.ticket.services.get_upload_path, validators=[apps.ticket.services.validate_file_extension], verbose_name='Фото чека'),
        ),
    ]
