# Generated by Django 3.2.9 on 2023-07-25 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_alter_ticket_chek_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Билет', 'verbose_name_plural': 'Билеты'},
        ),
        migrations.AlterModelTable(
            name='ticket',
            table='ticket',
        ),
    ]
