# Generated by Django 3.2.9 on 2023-08-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_auto_20230829_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='place',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 'Все 4')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='place_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Gold'), (2, 'Silver'), (3, 'Standart'), (4, 'Шатер Invest zone'), (5, 'Шатер Trade zone')], verbose_name='Статус места'),
        ),
    ]
