# Generated by Django 3.2.9 on 2023-07-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSMI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_certificate', models.ImageField(blank=True, null=True, upload_to='images/certificate-smi', verbose_name='Загрузите вашего журналистского удостоверения в  png или jpg')),
                ('image_logo', models.ImageField(blank=True, null=True, upload_to='images/logo-smi', verbose_name='Загрузите логотип компании в png или jpg')),
                ('quantity_person', models.CharField(blank=True, max_length=300, null=True, verbose_name='Сколько у вас человек в команде ?')),
                ('name_organization', models.CharField(blank=True, max_length=300, null=True, verbose_name='Полное юридическое наименование организации')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='Юридический адрес')),
                ('web_site', models.CharField(blank=True, max_length=300, null=True, verbose_name='Веб-сайт')),
                ('email_company', models.EmailField(blank=True, max_length=300, null=True, verbose_name='Email компании')),
                ('phone_smi', models.BigIntegerField(blank=True, max_length=32, null=True, verbose_name='Телефон')),
                ('uniqueId', models.UUIDField(blank=True, null=True, unique=True, verbose_name='Уникальный id')),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='Email')),
                ('instagram', models.CharField(blank=True, max_length=300, null=True, verbose_name='Instagram')),
                ('facebook', models.CharField(blank=True, max_length=300, null=True, verbose_name='Facebook')),
                ('twitter', models.CharField(blank=True, max_length=300, null=True, verbose_name='Twitter')),
                ('whatsapp_bool', models.BooleanField(default=False, verbose_name='WhatsApp')),
                ('telegram_bool', models.BooleanField(default=False, verbose_name='Telegram')),
                ('radio_bool', models.BooleanField(default=False, verbose_name='Радио реклама')),
                ('tv_bool', models.BooleanField(default=False, verbose_name='ТВ')),
                ('instagram_bool', models.BooleanField(default=False, verbose_name='Инстаграм')),
                ('invite_mail', models.BooleanField(default=False, verbose_name='Приглашение от организаторов по почте')),
                ('invite_fair', models.BooleanField(default=False, verbose_name='Приглашение от экспонента выставки')),
                ('invite_minister', models.BooleanField(default=False, verbose_name='Приглашение от Министерства / ведомства')),
                ('message', models.BooleanField(default=False, verbose_name='Сообщение по тел/факсу от организаторов')),
                ('ad_city', models.BooleanField(default=False, verbose_name='Наружная реклама в городе')),
                ('smi_bool_one', models.BooleanField(default=False, verbose_name='Стать частью информационной поддержки')),
                ('smi_bool_two', models.BooleanField(default=False, verbose_name='Знакомство с новыми компаниями')),
                ('smi_bool_three', models.BooleanField(default=False, verbose_name='Освещение и полезная информация')),
                ('smi_bool_four', models.BooleanField(default=False, verbose_name='Участие на пресс-конференции')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
