# Generated by Django 3.2.9 on 2023-07-26 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.user')),
                ('company_one', models.CharField(blank=True, max_length=300, null=True, verbose_name='Название компании')),
                ('company_two', models.CharField(blank=True, max_length=300, null=True, verbose_name='Юридическое название компании')),
                ('personnel', models.CharField(blank=True, max_length=300, null=True, verbose_name='Количество сотрудников')),
                ('industry', models.CharField(blank=True, choices=[['Информационные технологии и программное обеспечение.', 'Информационные технологии и программное обеспечение.'], ['Машиностроение и автоматизация производства.', 'Машиностроение и автоматизация производства.'], ['Медицинская и фармацевтическая промышленность.', 'Медицинская и фармацевтическая промышленность.'], ['Транспорт и логистика.', 'Транспорт и логистика.'], ['Пищевая и сельскохозяйственная промышленность.', 'Пищевая и сельскохозяйственная промышленность.'], ['Энергетика и альтернативные источники энергии.', 'Энергетика и альтернативные источники энергии.'], ['Финансовые и банковские продукты и услуги', 'Финансовые и банковские продукты и услуги'], ['Строительство и недвижимость', 'Строительство и недвижимость'], ['Образовательные продукты и услуги', 'Образовательные продукты и услуги'], ['Техника и спецтехника', 'Техника и спецтехника'], ['Классическое и современное искусство', 'Классическое и современное искусство'], ['Национальные товары, рукоделие, сувенирная продукция', 'Национальные товары, рукоделие, сувенирная продукция'], ['Экотовары', 'Экотовары'], ['Инвестиционные проекты', 'Инвестиционные проекты'], ['Другое', 'Другое']], default=None, max_length=300, null=True, verbose_name='Отрасль (Выберите одну из представленных “Строительство и недвижимость”)')),
                ('industry_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Другое(Введите свою отрасль если не нашли среди предложенных)')),
                ('direction', models.CharField(blank=True, max_length=300, null=True, verbose_name='Направление (Напишите свой вид деятельности “Производство кирпичей”)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опишите свою деятельность (товар или услугу)')),
                ('country', models.CharField(blank=True, max_length=128, null=True, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=128, null=True, verbose_name='Город')),
                ('address_one', models.CharField(blank=True, max_length=128, null=True, verbose_name='Юридический адрес')),
                ('address_two', models.CharField(blank=True, max_length=128, null=True, verbose_name='Фактический адрес')),
                ('email_company', models.EmailField(blank=True, max_length=128, null=True, verbose_name='Адрес электронной почты компании')),
                ('site_company', models.CharField(blank=True, max_length=300, null=True, verbose_name='Сайт')),
                ('instagram', models.CharField(blank=True, max_length=300, null=True, verbose_name='Instagram')),
                ('facebook', models.CharField(blank=True, max_length=300, null=True, verbose_name='Facebook')),
                ('iin_inn', models.CharField(blank=True, max_length=128, null=True, verbose_name='ИИН/ИНН(Серия патента компании)')),
                ('ogrn', models.CharField(blank=True, max_length=128, null=True, verbose_name='ОГРН(Номер патента)')),
                ('okpo', models.CharField(blank=True, max_length=128, null=True, verbose_name='ОКПО')),
                ('charter_company', models.FileField(blank=True, null=True, upload_to='company/% Y/% m/% d/', verbose_name='Загрузите устав компании в  pdf или jpg')),
                ('bank', models.CharField(blank=True, max_length=128, null=True, verbose_name='Наименование банка')),
                ('p_c', models.CharField(blank=True, max_length=128, null=True, verbose_name='P/C')),
                ('bik', models.CharField(blank=True, max_length=128, null=True, verbose_name='БИК')),
                ('image_logo', models.ImageField(blank=True, null=True, upload_to='images/logo-participant', verbose_name='Загрузите логотип компании в png или jpg')),
                ('name_manager', models.CharField(blank=True, max_length=128, null=True, verbose_name='Ф.И.О (Данные о руководителе)')),
                ('date_of_birth', models.CharField(blank=True, max_length=64, null=True, verbose_name='Дата рождения')),
                ('iin_inn_manage', models.CharField(blank=True, max_length=128, null=True, verbose_name='ИНН/ИИН руководителя')),
                ('position', models.CharField(blank=True, max_length=64, null=True, verbose_name='Должность')),
                ('effective', models.CharField(blank=True, max_length=128, null=True, verbose_name='Действующий на основании')),
                ('contact_person', models.BooleanField(default=False, verbose_name='Контактное лицо')),
                ('name_cont_person', models.CharField(blank=True, max_length=128, null=True, verbose_name='Ф.И.О (Контактное лицо)')),
                ('number_cont_person', models.BigIntegerField(blank=True, null=True, verbose_name='Номер телефона')),
                ('whatsapp_bool', models.BooleanField(default=False, verbose_name='WhatsApp')),
                ('telegram_bool', models.BooleanField(default=False, verbose_name='Telegram')),
                ('radio_bool', models.BooleanField(default=False, verbose_name='Радио реклама')),
                ('tv_bool', models.BooleanField(default=False, verbose_name='ТВ')),
                ('instagram_bool', models.BooleanField(default=False, verbose_name='Инстаграм')),
                ('invite_mail', models.BooleanField(default=False, verbose_name='Приглашение от организаторов по почте')),
                ('invite_fair', models.BooleanField(default=False, verbose_name='Приглашение от экспонента выставки')),
                ('invite_minister', models.BooleanField(default=False, verbose_name='Приглашение от Министерства / ведомства')),
                ('message', models.BooleanField(default=False, verbose_name='Сообщение по тел/факсу от организаторов')),
                ('ad_city', models.BooleanField(default=False, verbose_name='Наружная реклама в городе')),
                ('bool_company_one', models.BooleanField(default=False, verbose_name='Присутствие инвесторов')),
                ('bool_company_two', models.BooleanField(default=False, verbose_name='Присутствие государственных органов')),
                ('bool_company_three', models.BooleanField(default=False, verbose_name='Выход на мировой рынок')),
                ('bool_company_four', models.BooleanField(default=False, verbose_name='Реализация продукции')),
                ('bool_company_five', models.BooleanField(default=False, verbose_name='Возможность получения инвестиции')),
                ('bool_company_six', models.BooleanField(default=False, verbose_name='Расширение бизнеса')),
                ('bool_company_seven', models.BooleanField(default=False, verbose_name='Коммуникация с другми участниками')),
                ('bool_company_eight', models.BooleanField(default=False, verbose_name='Программа')),
                ('bool_company_nine', models.BooleanField(default=False, verbose_name='Место и формат проведения')),
                ('bool_company_ten', models.BooleanField(default=False, verbose_name='Возможность получения номинации')),
            ],
            options={
                'verbose_name': 'Пользователь СМИ',
                'verbose_name_plural': 'Пользователи СМИ',
            },
            bases=('users.user',),
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Все пользователи', 'verbose_name_plural': 'Пользователь'},
        ),
    ]
