# Generated by Django 3.2.9 on 2023-07-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230727_0144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expert',
            options={'verbose_name': 'Пользователь ЭКСПЕРТ', 'verbose_name_plural': 'Пользователи ЭКСПЕРТОВ'},
        ),
        migrations.AlterModelOptions(
            name='gosuser',
            options={'verbose_name': 'Пользователь ГОС-ОРГАНЫ', 'verbose_name_plural': 'Пользователи ГОС-ОРГАНОВ'},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'verbose_name': 'Пользователь УЧАСТНИК', 'verbose_name_plural': 'Пользователи УЧАСТНИКОВ'},
        ),
        migrations.AlterModelOptions(
            name='visitor',
            options={'verbose_name': 'Пользователь ПОСЕТИТЕЛЬ', 'verbose_name_plural': 'Пользователи ПОСЕТИТЕЛЕЙ'},
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'СМИ'), (2, 'ПОСЕТИТЕЛЬ'), (3, 'ЭКСПЕРТ'), (4, 'ГОС-ОРГАНЫ'), (5, 'УЧАСТНИК')], default=None, verbose_name='Тип пользователя'),
        ),
    ]
