# Generated by Django 3.2.9 on 2023-07-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usersmi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmi',
            name='phone_smi',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Телефон'),
        ),
    ]
