# Generated by Django 3.2.9 on 2023-07-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230727_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'СМИ'), (2, 'ПОСЕТИТЕЛЬ'), (3, 'ЭКСПЕРТ'), (4, 'ГОС-ОРГАНЫ'), (5, 'УЧАСТНИК')], default=2, verbose_name='Тип пользователя'),
        ),
    ]
