# Generated by Django 3.2.9 on 2023-07-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20230727_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(max_length=300, verbose_name='Дата Регистрация '),
        ),
    ]
