# Generated by Django 3.2.9 on 2023-07-27 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_user_type'),
        ('users', '0007_alter_user_date_joined'),
    ]

    operations = [
    ]
