# Generated by Django 3.2.9 on 2023-07-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_merge_20230727_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(blank=True, max_length=300, null=True, verbose_name='Дата Регистрация '),
        ),
    ]
