# Generated by Django 3.2.9 on 2023-07-31 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2b',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='b2b',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='b2b',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='b2b',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='expectation',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='expectation',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='expectation',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='expectation',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='partner',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='partner',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='partner',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='partner',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='smi',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='smi',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
    ]
