# Generated by Django 4.2.3 on 2023-07-22 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0002_alter_news_image_alter_partners_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Partners',
            new_name='Partner',
        ),
    ]
