# Generated by Django 3.2.9 on 2023-08-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
            },
        ),
        migrations.CreateModel(
            name='ParticipationSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(upload_to='media/food_zone', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Этап участия',
                'verbose_name_plural': 'Этапы участия',
                'db_table': 'participation_steps',
            },
        ),
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Название',
                'verbose_name_plural': 'Название',
                'db_table': 'terms',
            },
        ),
        migrations.CreateModel(
            name='FoodZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_title', models.CharField(max_length=300, verbose_name='Заглавный текст')),
                ('header_photo', models.ImageField(upload_to='media/food_zone', verbose_name='Заглавное фото')),
                ('advantage', models.ManyToManyField(related_name='food_zone_advantage', to='food_zone.Advantage')),
            ],
        ),
    ]
