# Generated by Django 3.2.9 on 2023-07-31 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest_zone', '0002_stand_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='advantage',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='advantage',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='conditions',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='conditions',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='conditions',
            name='signing_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Подописание'),
        ),
        migrations.AddField(
            model_name='conditions',
            name='signing_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Подописание'),
        ),
        migrations.AddField(
            model_name='conditions',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='conditions',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='generaladvantages',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='generaladvantages',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='generaladvantages',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='generaladvantages',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='investzone',
            name='block_title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Заглавный текст'),
        ),
        migrations.AddField(
            model_name='investzone',
            name='block_title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Заглавный текст'),
        ),
        migrations.AddField(
            model_name='investzone',
            name='header_photo_en',
            field=models.ImageField(null=True, upload_to='media/invest_zone', verbose_name='Заглавное фото'),
        ),
        migrations.AddField(
            model_name='investzone',
            name='header_photo_ru',
            field=models.ImageField(null=True, upload_to='media/invest_zone', verbose_name='Заглавное фото'),
        ),
        migrations.AddField(
            model_name='participationsteps',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='participationsteps',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='participationsteps',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='participationsteps',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='stand',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='stand',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='standzone',
            name='subtext_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Текст об окончании бронирования'),
        ),
        migrations.AddField(
            model_name='standzone',
            name='subtext_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Текст об окончании бронирования'),
        ),
        migrations.AddField(
            model_name='terms',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='terms',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Название'),
        ),
    ]
