# Generated by Django 3.2.9 on 2023-07-31 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_zone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionally',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='additionally',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='additionaltext',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='additionaltext',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='additionaltext',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Заглавный текст'),
        ),
        migrations.AddField(
            model_name='additionaltext',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Заглавный текст'),
        ),
        migrations.AddField(
            model_name='conditions',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='conditions',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='conditions',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Заглавный текст'),
        ),
        migrations.AddField(
            model_name='conditions',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Заглавный текст'),
        ),
        migrations.AddField(
            model_name='decor',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='decor',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='members',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='members',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='purchasestage',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Заглавный текст'),
        ),
        migrations.AddField(
            model_name='purchasestage',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Заглавный текст'),
        ),
        migrations.AddField(
            model_name='stand',
            name='title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='stand',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='standzone',
            name='block_description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='standzone',
            name='block_description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='standzone',
            name='block_title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Заглавный текст'),
        ),
        migrations.AddField(
            model_name='standzone',
            name='block_title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Заглавный текст'),
        ),
        migrations.AddField(
            model_name='standzone',
            name='photo_en',
            field=models.ManyToManyField(null=True, to='trade_zone.StandPhoto', verbose_name='Фото Стендов'),
        ),
        migrations.AddField(
            model_name='standzone',
            name='photo_ru',
            field=models.ManyToManyField(null=True, to='trade_zone.StandPhoto', verbose_name='Фото Стендов'),
        ),
        migrations.AddField(
            model_name='standzone',
            name='subtext_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Текст об окончании бронирования'),
        ),
        migrations.AddField(
            model_name='standzone',
            name='subtext_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Текст об окончании бронирования'),
        ),
        migrations.AddField(
            model_name='tradezone',
            name='block_title_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Заглавный текст'),
        ),
        migrations.AddField(
            model_name='tradezone',
            name='block_title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Заглавный текст'),
        ),
        migrations.AddField(
            model_name='tradezone',
            name='header_photo_en',
            field=models.ImageField(null=True, upload_to='media/trade_zone', verbose_name='Заглавное фото'),
        ),
        migrations.AddField(
            model_name='tradezone',
            name='header_photo_ru',
            field=models.ImageField(null=True, upload_to='media/trade_zone', verbose_name='Заглавное фото'),
        ),
    ]
