# Generated by Django 4.2.3 on 2023-07-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_zone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='standzone',
            name='subtext',
            field=models.CharField(default=1, max_length=300, verbose_name='Текст об окончании бронирования'),
            preserve_default=False,
        ),
    ]
