# Generated by Django 4.2.3 on 2023-07-21 10:15

import apps.investor.services
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название страны')),
                ('image', models.ImageField(upload_to=apps.investor.services.get_upload_path, verbose_name='Фото флага')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
                'db_table': 'investor_country',
            },
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=300, verbose_name='ФИО')),
                ('title', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.investor.services.get_upload_path, verbose_name='Фото представителя')),
            ],
            options={
                'verbose_name': 'Инвестор',
                'verbose_name_plural': 'Инвесторы',
                'db_table': 'investor',
            },
        ),
    ]
