# Generated by Django 3.2.9 on 2023-07-27 11:16

import apps.investor.services
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название страны')),
                ('image', models.ImageField(upload_to=apps.investor.services.get_upload_path, verbose_name='Фото флага')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
                'db_table': 'investor_country',
            },
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=300, verbose_name='ФИО')),
                ('title', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.investor.services.get_upload_path, verbose_name='Фото представителя')),
            ],
            options={
                'verbose_name': 'Инвестор',
                'verbose_name_plural': 'Инвесторы',
                'db_table': 'investor',
            },
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=999, verbose_name='Название  предпринимателей')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото иконки')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Инстаграм')),
                ('url', models.URLField(blank=True, max_length=300, null=True, verbose_name='Сайт')),
                ('text', models.TextField(verbose_name='Описание сайта')),
                ('galary', models.ImageField(upload_to='', verbose_name='Фото Галерея ')),
            ],
            options={
                'verbose_name': 'Об организаторах',
                'verbose_name_plural': 'Об организаторах',
            },
        ),
        migrations.CreateModel(
            name='Sponsors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_one', models.TextField(max_length=300, verbose_name='текст описание')),
                ('icon_one', models.ImageField(upload_to='', verbose_name='Иконка')),
                ('description', models.TextField(max_length=300, verbose_name='Описание сайта')),
            ],
            options={
                'verbose_name': 'Спонсоры',
                'verbose_name_plural': 'Спонсоры',
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание сайта')),
            ],
            options={
                'verbose_name': 'Описание',
                'verbose_name_plural': 'Описание',
                'db_table': 'investor_text',
            },
        ),
    ]
