# Generated by Django 4.2.3 on 2023-07-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание сайта')),
            ],
            options={
                'verbose_name': 'Описание',
                'verbose_name_plural': 'Описание',
                'db_table': 'investor_text',
            },
        ),
        migrations.RemoveField(
            model_name='country',
            name='description',
        ),
    ]
