# Generated by Django 3.2.9 on 2023-07-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investor', '0002_text_remove_country_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=999, verbose_name='Название  предпринимателей')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото иконка')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Инстаграм')),
                ('url', models.URLField(blank=True, max_length=300, null=True, verbose_name='Сайт')),
                ('text', models.TextField(verbose_name='Описание сайта')),
                ('galary', models.ImageField(upload_to='', verbose_name='Фото Галерея ')),
            ],
            options={
                'verbose_name': 'Об организаторах',
                'verbose_name_plural': 'Об организаторах',
            },
        ),
        migrations.CreateModel(
            name='Sponsors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_one', models.TextField(max_length=300, verbose_name='текст описание')),
                ('icon_one', models.ImageField(upload_to='', verbose_name='Иконка')),
                ('description', models.TextField(max_length=300, verbose_name='Описание сайта')),
            ],
            options={
                'verbose_name': 'Спонсоры',
                'verbose_name_plural': 'Спонсоры',
            },
        ),
    ]
