# Generated by Django 4.2.3 on 2023-07-25 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_message_receiver_alter_message_sender_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatroom',
            options={'verbose_name': 'Комната для чата', 'verbose_name_plural': 'Комнаты для чата'},
        ),
    ]
